### ISSUE TITLE
Sorting options?

### ISSUE THREAD

**Issue by for-coursera** [TUVIMEN/torge#1]
Would be great to support searching with various sorting options, too (e.g., by seeds, by date). Like, for 1337 the destination URL then would something like https://1337x.to/sort-search/LINUX%20ISO/time/desc/1/, and so on... Could be quite some additional work but sometimes you need the newest results first :(

BTW, in the demo you paste the selected result to `tnr`, what is it? Looks like some remote for Transmission? :)

All in all, great work, looks pretty handy!

**Comment by TUVIMEN** [comment]
Every source has additional `--help` page. Most of them have `-s` `--sort` option, in case of 1337x it can be sorted by `name`, `size`, `date`, `se` and `le`, sorting can be even reversed.

About `tnr` its just an alias to `transmission-remote`, but nowdays i use helper function integrating this script with `fzf`.

**Comment by for-coursera** [comment]
Thanks!
