### ISSUE TITLE
Anyway to speed this up?

### ISSUE THREAD

**Issue by ralyodio** [TUVIMEN/torge#13]
Is it possible to execute the fetch requests (or curl) in parallel?

https://chatgpt.com/share/66f71598-1b0c-8002-b80c-6ddf344473bd

It would speed them up a lot I think.

**Comment by TUVIMEN** [comment]
In normal use you make one request to search, and another to get link if site requires you to. So this would be only useful for `--link-conv` option, but parallel requests may trigger ddos protections. Thus i see no reason to add it.

For your use case it would be better to make your script run parallel for all providers so you don't get blocked. If you want to convert links in parallel you can change the `link_conv_out()` function (it's just a basic for loop so it should be easy).
