### ISSUE TITLE
Provider (1337x) bugs

### ISSUE THREAD

**Issue by Disonantemus** [TUVIMEN/torge#15]
1. Search phrase doesn't work:

~~~ocaml
$ torge 1337x "debian iso"
~~~

You get 20 results, none with `debian` word.
Totally different than web result:
https://1337x.to/search/debian+iso/1/

---

2. Not getting last results (maybe from same day):

~~~ocaml
$ torge 1337x -s date epub
~~~

First result you get, it's the same as page 4 results in web.
Not showing a lot of previous results:
https://1337x.to/sort-search/epub/time/desc/4/

----

Last versions of torge & reliq, everything else updated:
~~~ocaml
distro: Arch Linux x86_64
kernel: 6.6.52-1-lts
shell: bash 5.2.37
term: tmux
~~~

**Comment by ralyodio** [comment]
https://quzo.org/

**Comment by Disonantemus** [comment]
> https://quzo.org/

I did test your page, that appears to use `torge` (because has same providers and results), and got the same reported bugs:

1. Put "debian iso" and press `Search`:
    - In 1337x section, no results with anything "debian".

2. Changing to sort by `Time`, then put "epub" and press `Search`:
    - Results from 1337x section are wrong, should be the same as: 
    https://1337x.to/sort-search/epub/time/desc/4/

3. Reported in #14 
    - In rarbg section, if you press `copy` you don't get any magnet in clipboard.

---

Can you re-check and put your output?

**Comment by TUVIMEN** [comment]
Default domain for `1337x` is https://www.1337xx.to. Searching `debian iso` on it and on their tor domain gives weird results.

This works on `1337x.to`, `1337x.st` and `1337x.ws`. But `1337x.to` is blocked by every network protection. `1337x.st` and `1337x.ws` have cloudflare protection. Thus i can't change the default domain. 

You can change the used domain with `-d` option e.g. `torge 1337x -d "https://1337x.to" debian iso`.
