### ISSUE TITLE
[Feature] xsel as an alternative to xclip

### ISSUE THREAD

**Issue by Disonantemus** [TUVIMEN/torge#6]
I prefer [`xsel`](https://github.com/kfish/xsel) and was very easy to change the code, like this:

~~~ocaml
$ diff torge_xsel torge
543c537
<         echo "$results" | xsel
---
>         echo "$results" | xclip -r -sel clip
~~~

I think more people would like to have both options, maybe detecting which is present and use that.

**Comment by ralyodio** [comment]
I think xclip isn't on kde wayland either.

**Comment by TUVIMEN** [comment]
[Now](https://github.com/TUVIMEN/torge/commit/65b18ecbfd6d1b61946e4bc1458a7e07d78db05f) xsel will be used when xclip is not found.

**Comment by ralyodio** [comment]
awesome.
