### ISSUE TITLE
can you add 'provider' to initial results:

### ISSUE THREAD

**Issue by ralyodio** [TUVIMEN/torge#7]
```
#!/bin/sh

for i in tpb lt nyaa 1337x rarbg
do
    torge "$i" --no-prompt --link-conv -s date --json "$@"
done | jq -s '[ .[].results[] ]'
~                                   
```

I want to see the provider so on my search UI I can group results by provider.

**Comment by TUVIMEN** [comment]
The field was already there.

```
for i in tpb lt nyaa 1337x rarbg
do
    torge "$i" --no-prompt --link-conv -s date --json "$@"
done | jq -rcs '. | map({"provider":.site,"results":.results})'
```

**Comment by ralyodio** [comment]
its not there for me:

```
./all.sh 'metallica discography' | jq .
```

**Comment by ralyodio** [comment]
Your version works though, is there anyway to pass a category to `torge`?

**Comment by TUVIMEN** [comment]
Categories are supported only for `nyaa` and `rarbg`.

**Comment by TUVIMEN** [comment]
Nonetheless categories on sites are not universal

**Comment by TUVIMEN** [comment]
Support for categories has been [added](https://github.com/TUVIMEN/torge/commit/82cea3e0a38ec35f126e8da5c034ca259bd09735) to 1337x

**Comment by ralyodio** [comment]
can you add tpb too?

**Comment by TUVIMEN** [comment]
[Done](https://github.com/TUVIMEN/torge/commit/d91d6a05914a16d3308622fb1d770524e242ff63)

**Comment by ralyodio** [comment]
thanks
