### ISSUE TITLE
can you add a `--proxy` flag to torge with format of `http://user:pass@ip`

### ISSUE THREAD

**Issue by ralyodio** [TUVIMEN/torge#9]
can you add a `--proxy` flag to torge with format of `http://user:pass@ip`

_Originally posted by @ralyodio in https://github.com/TUVIMEN/torge/issues/8#issuecomment-2358892613_

**Comment by TUVIMEN** [comment]
`--proxy` option was [added](https://github.com/TUVIMEN/torge/commit/4762363ee2f52b33841fba1f20915d200629f8ac).
